### ISSUE TITLE
[providers] Introduce data model and API for providers

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2159]
This will contain something along these lines (copy pasted from earlier presentation/discussion):

A UCloud provider is defined by the following information:

1. __Metadata:__ Contains basic information about where to contact the provider. Immutable, cannot be changed later.
2. __Manifest:__ Contains information about the providers features. Mutable, can be changed on demand.

TODO INSERT PICTURE HERE

### Metadata

```yaml
id: aau-clauaadia
domain: clauaadia.aau.dk
https: true
env: production
```

All UCloud requests will be namespaced at `/ucloud/${id}`. This should allow it to easily live side-by-side with other HTTP endpoints. If HTTPS is in use then the page must use a valid TLS certificate signed by a commonly recognized certificate authority. `https` must be true if the `env` is `production`.  

### Manifest

```yaml
users:
  requireExplicitMapping: false # see below

features: # by default, all features are disabled
    compute:
        docker:
            enabled: true
            web: false
            vnc: false
            batch: true
            logs: true
            terminal: false

        virtualMachine:
            enabled: true
            logs: false
            vnc: false
            terminal: false

    storage:
      enabled: true
      shares: false
      projects: true

    blockDevices:
      enabled: true

    ipAddresses:
      enabled: true
```

The UCloud provider manifest is retrieved from: `GET ${PROTOCOL}://${DOMAIN}/ucloud/${id}/manifest`. The manifest is cached by UCloud. The provider can force a reload through the user interface or by sending a request to TODO.
