### ISSUE TITLE
[vms] Introduce a new VIRTUAL_MACHINE tool backend

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2162]
Copy pasted from earlier discussions

```yaml
---
tool: v1
name: ubuntu
version: 20.04

title: Ubuntu 20.04
description: Ubuntu is a Linux distribution based on Debian.
authors: ["Canonical Ltd."]

backend: VIRTUAL_MACHINE

# Reference to some image available at the provider:
# For openstack, the provider could assume that this image has been
# pre-configured by a sysadmin prior to adding this tool in UCloud
image: ubuntu20-04

# VIRTUAL_MACHINES are by default not supported by any provider
# DOCKER are by default supported by all providers (which declare support for
# docker). That is, public repo assumed.
supportedProviders:
- myprovider

---
application: v1
name: ubuntu
version: 20.04

title: Ubuntu 20.04
description: Ubuntu is a Linux distribution based on Debian.
authors: ["Canonical Ltd."]

tool:
  name: ubuntu
  version: 20.04

parameters:
  cloudInit:
    title: Cloud Init
    type: input_file
    description: >
      The Cloud Init file can initialize your virtual machine for your needs.
    optional: false

timeLimited: false # default for VMs
allowReplicas: false # default for VMs

# Applications can change which types of resources can be attached to it
#
# These can also be controlled by the provider manifest. That is, even 
# if an application supports a feature it must also be supported by the 
# provider
resources:
  allowBlockDevices: true # support block devices
  allowNetwork: true # support network resources (e.g. IP allocation)
  allowFiles: false # Don't support direct mounting of UCloud files
```
