### ISSUE TITLE
(Potential) Input validation error on application creation

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2618]
The following application has no port attached to web interface, yet it was accepted by UCloud. Investigate why this was successfully parsed and potentially issue a fix.

```
application: v1
​
title: Apache Superset 
name: superset  
version: 1.2.0-dev3a 
​
website: https://docs.cloud.sdu.dk/Apps/superset.html
​
applicationType: WEB
​
### WEB type
web:
  port: # default is 8088
​
# allowMultiNode: true
​
tool:
  name: superset  
  version: 1.2.0-dev3 
​
authors:
  - Maxime Beauchemin / Airbnb 
​
### A list of file extensions supported by this application
#fileExtensions:
​
### Support public Ips
# allowPublicIp: true
​
### Add default user to sudo group
# container:
#   runAsRoot: true
 
description: >
          Apache Superset is a modern data exploration and visualization platform able to handle data at petabyte scale (big data).
​
invocation:
  - start_superset
​
  - type: var
    vars: m_var
    prefixGlobal: '-m '
  - type: var
    vars: s_var
    prefixGlobal: '-s '
  - type: flag
    flag: '-a '
    var:  a_flag
  - type: flag
    flag: '-u '
    var:  u_flag
  - type: flag
    flag: '-l '
    var:  l_flag  
  
​
parameters:
  
  m_var:
    title: Additional dependencies
    type: input_file
    description: > 
             File with list of additional dependencies; available formats: *.sh (bash)
    optional: true  
  s_var:
    title: SUPERSET_HOME directory
    type: input_directory
    description: > 
             Directory on UCloud where configuration files (e.g. superset_config.py) and databases are stored
             (in the python PATH).  If empy a default configuration will be used.         
    optional: false
  a_flag: 
    title: 'Option: -a' 
    type: boolean
    description: > 
            Running first time setup for Superset, (default values: username admin, pwd admin)                  
    optional: true
  u_flag: 
    title: 'Option: -u'
    type: boolean
    description: > 
            Choose the password for admin (to be used with Create admin user)                               
    optional: true
  l_flag: 
    title:  'Option: -l'
    type: boolean
    description: > 
            Load examples
    optional: true
​
outputFileGlobs:
  - "*"
````
