### ISSUE TITLE
TLS support in apps with multiple 'interfaces'

### ISSUE THREAD

**Issue by Tobias-V** [SDU-eScience/UCloud#3709]
We have apps running on public IPs to be able to serve content on two different ports. We would like to offer TLS in apps such as this.

I believe the right approach is to use public links, but we can't currently do this with public links.

I think the right solution would be to allow an app to have multiple web interfaces, and to allow attaching a public link to each web interface.

The implementation in the YAML file could look something like this.

I would remove the `allowPublicLink` boolean

Then I would add another layer to `web` (interface1 and interface2 being the names of the interfaces)
```
web:
  interface1:
    port: 9000
    allowPublicLink: true
  interface2:
    port: 9001
    allowPublicLink: true
```
![Screenshot from 2022-10-04 12-52-34](https://user-images.githubusercontent.com/44464613/193801440-f7084f9a-6ee3-469e-a040-dc15dcb5bfc2.png)

On the UCloud end, I'd change this to show a list of the interfaces with allowPublicLink set to true, and have an 'Add public link' for each entry.
